# conf/generalist.yaml
# PHASE 1: Unified Generalist configuration.

defaults:
  - /dataset: default
  - _self_

# --- Experiment Metadata ---
run_name: "gen_v1_${now:%Y-%m-%d_%H-%M-%S}"
seed: 42
compile_model: false

# --- Directory Paths ---
output_dir: "outputs/phase1"           # Main output directory
checkpoint_dir: "outputs/phase1/checkpoints"  # Where checkpoints are saved
log_dir: "/content/drive/MyDrive/icu/logs/"         # Training logs directory
backup_dir: null                        # Remote/backup directory
resume_from: null                       # Explicit checkpoint to resume from (optional)

# --- Model Architecture (ICUUnifiedPlanner) ---
model:
  input_dim: 28
  static_dim: 6
  history_len: 24
  pred_len: 6
  d_model: 768
  n_heads: 12
  n_layers: 8
  encoder_layers: 4
  ffn_dim_ratio: 4
  dropout: 0.1
  use_rope: true
  use_swiglu: true
  use_flash_attn: true
  gradient_checkpointing: true
  timesteps: 100
  beta_schedule: "cosine"
  prediction_type: "epsilon"
  use_ddim_sampling: true
  use_auxiliary_head: true
  num_phases: 6 # SOTA-Clinical: 2 sub-experts per natural phase (Stable, Pre-Shock, Shock)

# --- Training Hyperparameters ---
train:
  phase: "phase1"
  epochs: 100
  batch_size: 512             # [USER REQUEST] Halved from 1024 due to worker bottleneck
  num_workers: 2
  lr: 2.0e-4
  min_lr: 1e-6
  warmup_steps: 500
  weight_decay: 1e-4
  grad_clip: 1.0
  pos_weight: 32.96 # Optimized v2.0 (1:33 Imbalance)
  aux_loss_scale: 0.182
  precision: "16-mixed"
  accumulate_grad_batches: 2  # [AUTO] Maintain effective batch size of 1024 (512 * 2)
  log_every_n_steps: 10
  val_batches: 50  # Number of validation batches per epoch
  
  # AWR (Advantage Weighted Regression) v2.0 (Globally Optimal via Exhaustive Audit)
  awr_beta: 0.400             # Optimized v2.0 (High Selectivity)
  awr_max_weight: 20.0        # Optimized v2.0 (Outlier Guard)
  
  # AWR Calibration Speed/Quality (v10.1 Upgrade)
  # - "full": Scans all trajectories (~5-10 min, best for final training)
  # - "sample": Random subset (~10-30 sec, best for testing)
  awr_calibration_mode: "sample" # full for whole population scan
  awr_max_samples: 5000       # Only used if mode="sample" it will be ignored if awr_calibration_mode="full"
  
  # EMA (Exponential Moving Average)
  ema_decay: 0.9999
  monitor: "val/clinical_auroc"
  patience: 10
  
  # Optimization Groups
  backbone_lr_ratio: 1.0
  backbone_modules:
    - "encoder"
    - "backbone"

# --- Logging ---
logging:
  use_wandb: true
  wandb_project: "icu-diffusion-phase1"
  wandb_mode: "offline"
  run_name: ${run_name}
