# conf/generalist.yaml
# PHASE 1: Unified Generalist configuration.

defaults:
  - /dataset: default
  - _self_

# --- Experiment Metadata ---
run_name: "gen_v1_${now:%Y-%m-%d_%H-%M-%S}"
seed: 42
compile_model: true
save_checkpoints: false

# --- Directory Paths ---
output_dir: "outputs/phase1"           # Main output directory
checkpoint_dir: "/content/drive/MyDrive/pda/icu/checkpoints"  # Where checkpoints are saved
log_dir: "/content/drive/MyDrive/pda/icu/logs/icu"         # Training logs directory
backup_dir: null                        # Remote/backup directory
resume_from: null             # Explicit checkpoint to resume from (optional)
# "/content/drive/MyDrive/pda/models/checkpoints/icu_model-epoch=05-val/clinical_auroc=0.747.ckpt"          
# --- Model Architecture (ICUUnifiedPlanner) ---
model:
  input_dim: 28
  static_dim: 6
  history_len: 24
  pred_len: 6
  d_model: 768
  n_heads: 12
  n_layers: 8
  encoder_layers: 4
  ffn_dim_ratio: 4
  dropout: 0.25      # [NERYVA-ALPHA] High generalization threshold from Trial 20
  use_rope: true
  use_swiglu: true
  use_flash_attn: true
  gradient_checkpointing: false # [FIX] Conflict with torch.compile on T4/old drivers
  timesteps: 100
  beta_schedule: "cosine"
  prediction_type: "epsilon"
  use_ddim_sampling: true
  use_auxiliary_head: true
  num_phases: 6 # SOTA-Clinical: 2 sub-experts per natural phase (Stable, Pre-Shock, Shock)

# --- Training Hyperparameters ---
train:
  phase: "phase1"
  epochs: 100
  batch_size: 256           # [v20.6] Increased update frequency for classification signal
  num_workers: 2
  lr: 1.5e-4                  # [NERYVA-ALPHA] Optimal tempo for sepsis innovation
  min_lr: 1e-6
  warmup_steps: 500
  weight_decay: 1e-4
  grad_clip: 1.0

  pos_weight: 34.85           # [NERYVA-ALPHA] Certified Sensitivity (Trial 10 + 20 Synthesis)
  aux_loss_scale: 0.45        # [v12.5.1] Boosted for Expert Visibility
  precision: "16-mixed"
  accumulate_grad_batches: 1  
  log_every_n_steps: 10
  fused_optimizer: true       # [H100] Enable fused kernels 
  
  balancing_mode: "sota_2025" 
  uw_lr: 0.025                # Learning rate for uncertainty weights
  
  # Phase 3: Longitudinal Foresight (Agentic Convergence)
  start_gamma: 0.92           # [v25.9 SOTA] Stabilized for Unleashed Run
  end_gamma: 0.92             # [v25.9 SOTA] Parked at 12.5h for initial phase
  horizon_warmup: 10
  horizon_ramp: 40

  # Debug Mode (Smoke Test)
  debug_run: true
  debug_limit_batches: 100
  debug_limit_val: 500

  
  # AWR (Advantage Weighted Regression) v2.0
  awr_beta: 0.60              # [v12.5.1] Increased for Broad Discovery (ESS Stabilization)
  awr_max_weight: 20.0        
  awr_lambda: 0.95            # [SOTA] GAE-Lambda for credit assignment
  awr_gamma: 0.92             # [v25.9 SOTA] Synchronized with Horizon Manifold
  adaptive_beta: true
  adaptive_clipping: true
  
  # AWR Calibration Speed/Quality (v10.1 Upgrade)
  # - "full": Scans all trajectories (~5-10 min, best for final training)
  # - "sample": Random subset (~10-30 sec, best for testing)
  awr_calibration_mode: "sample" # full for whole population scan
  awr_max_samples: 20000      # [STABILITY] Increased for Batch 2048
  
  ema_decay: 0.999
  monitor: "val/clinical_auroc"
  patience: 10

  # Clinical Supervision (BGSL)
  trend_coef: 1.0             # Velocity penalty
  shock_coef: 2.0             # Acceleration/Surprise penalty
  
  # Contrastive Memory & Archetypes
  tcb_capacity: 1024          # Bank size for hard negatives
  tcb_temp: 0.07              # Cluster sharpness
  acl_centroid_reg: 0.05      # [v12.5.1] Higher to prevent contrastive collapse
  
  # Risk-Aware Asymmetric Loss
  asl_gamma_neg: 4.0          # Sepsis focusing weight
  asl_gamma_pos: 1.0          # Standard focusing
  risk_multiplier: 2.0        # Red-Zone penalty scale
  
  # Optimization Groups
  backbone_lr_ratio: 1.0
  backbone_modules:
    - "encoder"
    - "backbone"

# --- Logging ---
logging:
  use_wandb: true
  wandb_project: "icu-diffusion-phase1"
  wandb_mode: "offline"
  run_name: ${run_name}